version = 0.1
[default.deploy.parameters]
stack_name = "portamento-app"
s3_prefix = "portamento-app"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PortamentoBucketName=\"portamento-bucket\""
resolve_s3 = true
resolve_image_repos = true