AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Template for Portamento. One SQS, one S3. Lambda that sends messages to the SQS for every playlist. Lambda that fetches every playlist. The batch size of the song fetcher needs to be 1 (i.e. it will parse one single batch), because of timeout reasons in handling the fetch.

Resources:
  PortamentoPlaylistProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: portamento_playlist_processor
      Role: arn:aws:iam::000000000000:role/lambda-ex
      PackageType: Image
      ImageUri: portamento_playlist_processor
      Timeout: 10
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*

  PortamentoSongFetcher:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: portamento_song_fetcher
      Role: arn:aws:iam::000000000000:role/lambda-ex
      PackageType: Image
      ImageUri: portamento_song_fetcher
      Timeout: 10
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue.Arn
            BatchSize: 1

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: portamento-bucket

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: portamento-queue